apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 623474980943.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 623474980943.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: f49056e9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
